"""empty message

Revision ID: ca44b0fc9f41
Revises: d676ff538a1c
Create Date: 2016-09-10 21:32:07.949976

"""

# revision identifiers, used by Alembic.
revision = 'ca44b0fc9f41'
down_revision = 'd676ff538a1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_articles')
    ### end Alembic commands ###
