"""empty message

Revision ID: d7ebe2c792a6
Revises: dc7b5c6be91a
Create Date: 2016-09-11 00:42:34.437271

"""

# revision identifiers, used by Alembic.
revision = 'd7ebe2c792a6'
down_revision = 'dc7b5c6be91a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('website', sa.String(), nullable=True))
    op.add_column('fav_articles', sa.Column('website', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fav_articles', 'website')
    op.drop_column('articles', 'website')
    ### end Alembic commands ###
