"""empty message

Revision ID: dc7b5c6be91a
Revises: ca44b0fc9f41
Create Date: 2016-09-10 22:11:55.396940

"""

# revision identifiers, used by Alembic.
revision = 'dc7b5c6be91a'
down_revision = 'ca44b0fc9f41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image', sa.String(), nullable=True))
    op.add_column('fav_articles', sa.Column('image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fav_articles', 'image')
    op.drop_column('articles', 'image')
    ### end Alembic commands ###
